name: hackerdeck
description: Gamedeck PC
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^6.1.1
  path: ^1.9.0

flutter:
  uses-material-design: true
